ci(e2e): manually split cypress tests to improve speed (#7558)
* ci(e2e): manually split cypress tests to improve speed

This change simply lists the spec dir for e2e tests, chunks them into
5, and passes these specs to cypress explicitly.

I initially tried to use https://github.com/kamilkisiela/split-tests/blob/master/packages/cypress/README.md
but ran into

```
We invoked the function exported by `/home/runner/work/posthog/posthog/cypress/plugins/index.js`, but it threw an error.

 TypeError: Cannot read property 'mochaFile' of null
    at loadReports (/home/runner/work/posthog/posthog/node_modules/dist/cypress/src/index.js:14:44)
    at module.exports (/home/runner/work/posthog/posthog/node_modules/dist/cypress/src/index.js:44:19)
    at module.exports (/home/runner/work/posthog/posthog/cypress/plugins/index.js:27:14)
    at /home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:96:12
    at tryCatcher (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:93:7)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:204:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (/home/runner/.cache/Cypress/6.7.0/Cypress/resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

And so decided to go for something "simpler"

See for details https://github.com/PostHog/posthog/runs/4443218344?check_suite_focus=true

* run on master, ensures node_modules cache in scope

* run deps install on master

* increase concurrency

* run yarn install in prep section

* move if to job

* still run yarn install

* refactor

* comments

* change name so we don't have to update requirements

* Update e2e.yml

Co-authored-by: Tim Glaser <tim@posthog.com>